[package]
name = "nos-followers"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
axum = "0.7.5"
cached = { version = "0.53.1", features = ["async"] }
chrono = { version = "0.4.38", features = ["serde"] }
config_rs = { version = "0.14", package = "config", features = ["yaml"] }
futures = "0.3.30"
gcloud-sdk = { version = "0.25.5", features = ["google-pubsub-v1"] }
governor = "0.6.3"
metrics = "0.23.0"
metrics-exporter-prometheus = "0.15.3"
neo4rs = "0.8.0"
nostr-sdk = "0.33.0"
ordermap = "0.5.3"
rustls = { version = "0.23.12", features = ["ring"] }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
thiserror = "1.0.63"
time = "0.3.36"
tokio = { version = "1.39.3", features = ["full", "test-util"] }
tokio-util = { version = "0.7.11", features = ["rt"] }
tower-http = { version = "0.5.2", features = ["timeout", "trace"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[dev-dependencies]
assertables = "7.0.1"
pretty_assertions = "1.2"
