[package]
name = "nos-followers"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
cached = { version = "0.53.1", features = ["async"] }
chrono = { version = "0.4.38", features = ["serde"] }
config = "0.14.0"
env_logger = "0.11.5"
futures = "0.3.30"
nostr-sdk = "0.33.0"
rand = { version = "0.8.5", features = ["std"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.121"
sqlx = { version = "0.8.0", features = ["chrono", "postgres", "runtime-tokio", "time", "tls-native-tls"] }
time = "0.3.36"
tokio = { version = "1.39.2", features = ["full"] }
tokio-util = { version = "0.7.11", features = ["rt"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
