# A compose file to ease local development
services:
  server:
    build:
      context: .
      target: final
    environment:
      - APP__NEO4J_URI=db:7687
      - APP__NEO4J_USER=neo4j
      - APP__NEO4J_PASSWORD=mydevpassword
      - RUST_LOG=nos_followers=debug
      - RUST_BACKTRACE=1
    volumes:
      - ./config:/app/config
      - ./migrations:/app/migrations
      - cargo-registry:/usr/local/cargo/registry
      - cargo-git:/usr/local/cargo/git/db
      - build-cache:/app/target
    depends_on:
      db:
        condition: service_healthy
    restart: always
    attach: true

  relay:
    image: ghcr.io/planetary-social/nosrelay:latest
    ports:
      - "7777:7777"

  db:
    image: neo4j:latest
    platform: linux/amd64
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/mydevpassword
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    volumes:
      - db-data:/data
      - db-logs:/logs
      - db-import:/var/lib/neo4j/import
      - db-plugins:/plugins
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s

volumes:
  db-data:
  db-logs:
  db-import:
  db-plugins:
  cargo-registry:
  cargo-git:
  build-cache: