followers:
  relay: wss://relay.nos.social
  neo4j_uri:  "db:7687"
  neo4j_user: "neo4j"
  neo4j_password: "mydevpassword"
  http_port: 3000
  tcp_importer_port: 3001
  event_channel_size: 1000
  diff_workers: 1000
  follow_change_channel_size: 50000
  follow_change_workers: 30
  worker_timeout_secs: 15
  google_project_id: "pub-verse-app"
  google_topic: "follow-changes"
  flush_period_seconds: 60 # how often to flush the buffer to generate messages
  min_seconds_between_messages: 1800 # 30 minutes, so no more than 2 messages per hour
  pagerank_cron_expression: "0 0 0 * * *" # Daily at midnight
  http_cache_seconds: 86400 # 24 hours