followers:
  relay: wss://relay.nos.social
  neo4j_uri:  "db:7687"
  neo4j_user: "neo4j"
  neo4j_password: "mydevpassword"
  event_channel_size: 500
  diff_workers: 20
  follow_change_channel_size: 50000
  follow_change_workers: 30
  worker_timeout_secs: 15
  google_project_id: "pub-verse-app"
  google_topic: "follow-changes"
  flush_period_seconds: 60
  # 30 minutes, so no more than 2 messages per hour
  min_seconds_between_messages: 1800